#accessing baselibs image
FROM ubuntu-baselibs:6.3.1

MAINTAINER zain jerath <zainjerath@gmail.com>

#from mathomp4
RUN cd / && \
    git clone https://github.com/ESMCI/manage_externals.git && \
    cd manage_externals && \
    cd / && \
    git clone https://github.com/GEOS-ESM/mepo.git && \
    cd mepo

ENV PATH /mepo:/manage_externals:$PATH

#build command: docker build -f Dockerfile.geos-env -t ubuntu-geos-env:6.3.1 .
